spring.application.name=ShortBrew
spring.threads.virtual.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/shortbrew
spring.datasource.username=postgres
spring.datasource.password=password

# Connect to Redis container
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Connect to RabbitMQ container
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672