spring.application.name=ShortBrew
spring.threads.virtual.enabled=true

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:shortbrew}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:password}

# Connect to Redis container
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Connect to RabbitMQ container
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}

# Expose health check (for Nginx) and prometheus metrics endpoints
management.endpoints.web.exposure.include=health,prometheus
# Show detailed health components (Redis status, Database status, RabbitMQ status)
management.endpoint.health.show-details=always